Popups.ok=OK
Popups.cancel=Annuleren
Popups.error=Fout

ComboFileDialog.defaultOpenTitle=Bestand openen...
ComboFileDialog.defaultSaveTitle=Bestand opslaan...
ComboFileDialog.illegalChars=Ongeldige bestandsnaam.
ComboFileDialog.invalidExt=Selecteer een bestandsnaam met één van deze extensies: {0}.
ComboFileDialog.overwrite=Het bestand '{0}' bestaat al.\nOverschrijven?
ComboFileDialog.overwriteYes=Overschrijven
ComboFileDialog.overwriteNo=Annuleren
ComboFileDialog.allFiles=Alle bestanden

PropertyEditor.name=Naam
PropertyEditor.value=Waarde
PropertyEditor.add=+
PropertyEditor.edit=\u270E
PropertyEditor.remove=\u00D7
PropertyEditor.addTitle=Veld toevoegen
PropertyEditor.addName=Naam:
PropertyEditor.addValue=Waarde:
PropertyEditor.editTitle=Veld wijzigen
PropertyEditor.noPropertySelected=Geen veld geselecteerd.
PropertyEditor.save=Opslaan
PropertyEditor.cancel=Annuleren

FormPanel.save=Opslaan
FormPanel.cancel=Annuleren
