future=in de toekomst
now=nu
second=nu
seconds=een paar seconden geleden
minute=één minuut geleden
minutes={0} minuten geleden
hour=één uur geleden
hours={0} uur geleden
day=gisteren
days={0} dagen geleden
week=vorige week
weeks={0} weken geleden
month=vorige maand
months={0} maanden geleden
year=vorig jaar
years={0} jaar geleden
