name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: colorize-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: gradle compileJava
      - name: Unit tests
        run: gradle coverage
